name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller PacMan.spec
          
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          name: PacMan ${{ github.ref_name }}
          files: ./dist/PacMan.exe
          draft: false
          prerelease: false
          body: |
            # PacMan Game ${{ github.ref_name }}
            
            A classic PacMan clone built with Pygame.
            
            ## Controls
            - Arrow keys: Move Pac-Man
            - Space: Pause/unpause the game
            - ESC: Exit the game
            
            ## Features
            - Classic PacMan gameplay with authentic graphics and sounds
            - Multiple maze levels
            - Ghost AI with different personalities
            - Power pellets and fruit bonuses
            
            ## Requirements
            - Windows 10 or newer
            
            ## Download
            - Just download PacMan.exe and run it!
